### ISSUE TITLE
eyelinkReader::plot fails to install, even though other functions do install

### ISSUE THREAD

**Issue by alexholcombe** [alexander-pastukhov/eyelinkReader#3] opened 2024-05-27 02:29 UTC
I somehow have discovered a new failure mode, wherein all the basic functions install, except for plot, such that invoking plot, e.g. with  ``` eyelinkReader::plot ``, yields: 

``` Error: 'plot' is not an exported object from 'namespace:eyelinkReader'  ```

One can see the other functions that are installed, e.g. with ``` lsf.str("package:eyelinkReader") ```:

```

adjust_message_time : function (object, prefix)  
check_consistency_flag : function (consistency)  
check_logical_flag : function (logical_flag)  
check_string_parameter : function (string_parameter)  
check_that_compiled : function (fail_loudly = TRUE)  
compiled_library_status : function ()  
compute_cyclopean_samples : function (object, fun = mean)  
convert_header_codes : function (trial_headers)  
convert_NAs : function (original_frame)  
convert_recording_codes : function (trial_recordings)  
extract_AOIs : function (object)  
extract_blinks : function (object)  
extract_display_coords : function (object, message_prefix = "DISPLAY_COORDS", silent = FALSE)  
extract_fixations : function (object)  
extract_saccades : function (object)  
extract_triggers : function (object, message_prefix = "TRIGGER")  
extract_variables : function (object)  
logical_index_for_sample_attributes : function (import_samples, sample_attributes)  
read_edf : function (file, consistency = "check consistency and report", import_events = TRUE, 
    import_recordings = TRUE, import_samples = FALSE, sample_attributes = NULL, 
    start_marker = "TRIALID", end_marker = "TRIAL_RESULT", import_saccades = TRUE, 
    import_blinks = TRUE, import_fixations = TRUE, import_variables = TRUE, 
    verbose = TRUE, fail_loudly = TRUE)  
read_edf_file : function (filename, consistency, import_events, import_recordings, 
    import_samples, sample_attr_flag, start_marker_string, end_marker_string, 
    verbose)  
read_preamble : function (file, fail_loudly = TRUE)  
read_preamble_str : function (filename)  

```

I've tried uninstalling R, and RStudio, and re-installing Can't figure out why this doesn't work anymore even though I had it working before (with my fork that fixes the path problem on Mac).  Any ideas?

**Comment by alexholcombe** [comment] 2024-05-28 05:58
I've discovered that ` eyelinkReader:::plot ` (three colons to access private functions) doesn't work,
` eyelinkReader:::plot.eyelinkRecording ` does work, and the function successfully executes, e.g. 

```
data(gaze)
eyelinkReader:::plot.eyelinkRecording(gaze)
```
So, a good workaround for the problem is to simply use `plot.eyelinkRecording` in place of `plot`

**Comment by alexander-pastukhov** [comment] 2024-05-31 10:44
@alexholcombe Hi, sorry, distracted by an urgent project. Will take a look at both issues and do my best fixing them!

**Comment by alexander-pastukhov** [comment] 2024-09-27 11:48
@alexholcombe As with other issue, terribly sorry. Could you please check that the issue is fixed for you for github version? It now works for me.

**Comment by alexander-pastukhov** [comment] 2024-10-08 08:56
Tested on Windows and Mac, closing as resolved.

**Closed as completed by alexander-pastukhov** 2024-10-08 08:56 UTC
